import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'PALDOMOA-TEAM',
  description: 'Generated by create next app',
}

export default function Recruit() {
  return <h2> 나는 이거다</h2>
}
