spring:
  thymeleaf:
    prefix: classpath:templates/
    check-template: true
    suffix: .html
    mode: HTML
    cache: false

  datasource:
    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=gacd244e318caee_nolgugadb_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    driver-class-name: oracle.jdbc.OracleDriver
    username: PALDOMOA
    password: Qlrkfekr12##

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        #        show_sql: true
        format_sql: true
        use_sql_comments: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type: trace

  jwt:
    secret: OMEKDJGNAQJJPALDOMKQWNENQWEMOA1023KAJNDKJQNE12308qkwjenasjkdn12390812ejkqnweuhafpoqwpeqweqweknmxzc